# Generated by Django 5.0.4 on 2026-04-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='arbitro',
            name='category',
        ),
        migrations.AddField(
            model_name='designacion',
            name='rol_asignado',
            field=models.CharField(choices=[('ARBITRO_1', 'Árbitro 1'), ('ARBITRO_2', 'Árbitro 2'), ('MESA', 'Mesa de Control')], default='ARBITRO_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='categoria_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.categoria'),
        ),
        migrations.AddField(
            model_name='partido',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='gestion.categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='gestion.categoriagrupo'),
        ),
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ARBITRO', 'Árbitro'), ('MESA', 'Mesa de Control')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aranceles', to='gestion.categoriagrupo')),
            ],
            options={
                'unique_together': {('rol', 'categoria_grupo')},
            },
        ),
    ]
