# Generated by Django 5.0.4 on 2026-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_categoria_categoriagrupo_remove_arbitro_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='cbu_alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CBU / Alias'),
        ),
    ]
